apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: crm-ingress
  namespace: default
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: frontend
          namespace: crm