apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: learn-consul-k-s-hashicups
deploy:
  kubectl:
    manifests:
    - crds-ent/apps/*.yaml
    - hashicups-ent/apps/*.yaml
    defaultNamespace: apps

