apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend
spec:
  protocol: "http"
  upstreamConfig:
    defaults:
      protocol: "http"
      connectTimeoutMs: 30000
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: order-api
spec:
  protocol: "http"
  upstreamConfig:
    defaults:
      protocol: "http"
      connectTimeoutMs: 30000
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: product-api
spec:
  protocol: "http"
  upstreamConfig:
    defaults:
      protocol: "http"
      connectTimeoutMs: 30000