apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: frontend
  namespace: sales
spec:
  defaultSubset: v1
  connectTimeout: 30s
  subsets:
    v1:
      filter: "Service.Meta.version == v1"