{
 "title": "Resiliency Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Circuit Breaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Circuit Breaker detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "envoy_cluster_outlier_detection_ejections_active",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Circuit Breaker due to consecutive 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "envoy_cluster_outlier_detection_ejections_enforced_consecutive_5xx{kubernetes_namespace=\"apps\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Timeout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Timeout from Frontend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_timeout{kubernetes_namespace=\"apps\", consul_source_service=\"frontend\",consul_datacenter=\"dc1\"}",
     "legendFormat": "Destination service: {{consul_destination_service}}"
    }
   ]
  },
  {
   "title": "Request Timeout on Order API",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_timeout{kubernetes_namespace=\"apps\",consul_destination_service=\"order-api\"}",
     "legendFormat": "Source service: {{consul_source_service}}"
    }
   ]
  },
  { "title": "Retry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Detected Success Retry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_retry_success{kubernetes_namespace=\"apps\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Detected Request Retry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_retry{kubernetes_namespace=\"apps\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}