adminPassword: password

rbac:
  create: true
  pspEnabled: true
  namespaced: true
  extraRoleRules: 
   - apiGroups: [""]
     resources: ["configmaps","secrets"]
     verbs: ["watch","list","get"]

# Disable test pods
testFramework:
  enabled: false

podLabels:
  app: grafana

podAnnotations:
  "consul.hashicorp.com/connect-inject": "false"

service:
  port: 3000

sidecar:
  dashboards: 
    enabled : true

# Configure the prometheus data source. We expect prometheus:9090 in the same namespace.
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        orgId: 1
        url: prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: 5s
        editable: true

namespaceOverride: monitoring