apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api
---
# Service to expose web product-api
apiVersion: v1
kind: Service
metadata:
  name: product-api
spec:
  selector:
    app: product-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-deployment
  labels:
    app: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      serviceAccountName: product-api
      containers:
        - name: product-api
          image: nicholasjackson/fake-service:v0.22.7
          resources:
            limits:
              cpu: 50m
              memory: 32Mi 
          ports:
            - containerPort: 80
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:80'
            - name: 'NAME'
              value: 'product-api'
            - name: 'MESSAGE'
              value: 'Hello World'
            - name: 'TIMING_50_PERCENTILE'
              value: '16s'