apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: order-api
  namespace: apps
spec:
  destination:
    name: order-api
  sources:
    - name: frontend
      namespace: apps
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: product-api
  namespace: apps
spec:
  destination:
    name: product-api
  sources:
    - name: frontend
      namespace: apps
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
  namespace: apps
spec:
  destination:
    name: frontend
    namespace: apps
  sources:
    - name: ingress-gateway
      namespace: default
      action: allow