apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-api
---
# Service to expose web customer-api
apiVersion: v1
kind: Service
metadata:
  name: customer-api
spec:
  selector:
    app: customer-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api-deployment
  labels:
    app: customer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      serviceAccountName: customer-api
      containers:
        - name: customer-api
          image: nicholasjackson/fake-service:v0.22.7
          resources:
            limits:
              cpu: 50m
              memory: 32Mi 
          ports:
            - containerPort: 80
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:80'
            - name: 'NAME'
              value: 'customer-api'
            - name: 'MESSAGE'
              value: 'Hello World'