apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
# Service to expose web frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'customer-api:9091,partner-api:9092'
        'consul.hashicorp.com/service-meta-version': 'v1'
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: nicholasjackson/fake-service:v0.22.7
          resources:
            limits:
              cpu: 50m
              memory: 32Mi 
          ports:
            - containerPort: 80
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:80'
            - name: 'UPSTREAM_URIS'
              value: 'http://localhost:9091,http://localhost:9092'
            - name: 'NAME'
              value: 'frontend v1'
            - name: 'MESSAGE'
              value: 'Hello World - V1'