apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: frontend
  namespace: crm
spec:
  splits:
    - weight: 80
      serviceSubset: v1
    - weight: 20
      serviceSubset: v2