apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: partner-api
  namespace: crm
spec:
  destination:
    name: partner-api
  sources:
    - name: frontend
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: customer-api
  namespace: crm
spec:
  destination:
    name: customer-api
  sources:
    - name: frontend
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
  namespace: crm
spec:
  destination:
    name: frontend
    namespace: crm
  sources:
    - name: crm-ingress
      namespace: default
      action: allow